name: react-native-android-build-apk
on:
  pull_request:
    branches:
      - qa
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  send_to_google_chat:
    needs: build-android
    name: Send to Google Chat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/-/jobs/$GITHUB_RUN_ID/artifacts/$ARTIFACT_NAME

      - name: Send Artifact to Google Chat
        env:
          GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GCHAT_WEBHOOK }}
        run: |
          ARTIFACT_URL=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"text\": \"Artifact link: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/suites/$GITHUB_WORKFLOW_IDartifacts/$GITHUB_RUN_ID\"}" $GOOGLE_CHAT_WEBHOOK_URL)
          echo "Android Build : $ARTIFACT_URL"
          
          
